import streamlit as st
import pandas as pd
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from models import init_db, engine, Course, Venue
from genetic_algorithm import generate_optimal_timetable

# ==========================================
# HELPER FUNCTIONS
# ==========================================

def display_timetable_grid(raw_timetable_df):
    """
    Transforms a flat, unpivoted timetable DataFrame into a standard 2D grid format.
    Rows represent Time Slots, and Columns represent Days.
    
    Args:
        raw_timetable_df (pd.DataFrame): The raw schedule generated by the algorithm.
    """
    st.markdown("#### 📅 Grid Matrix View")
    
    df = raw_timetable_df.copy()
    
    # Concatenate course, venue, and lecturer information into a single string for cell display
    df['Cell_Info'] = df['Course Code'] + "\n📍 " + df['Allocated Venue(s)'].astype(str) + "\n👨‍🏫 " + df['Lecturer'].astype(str)
    
    # Group records by Time and Day. If multiple courses occur concurrently (e.g., across 
    # different departments), join their string representations with a visual separator.
    grouped_df = df.groupby(['Time', 'Day'])['Cell_Info'].apply(lambda x: '\n\n---\n\n'.join(x)).reset_index()
    
    # Pivot the dataframe to create the grid structure (Rows: Time, Columns: Day)
    grid_df = grouped_df.pivot(index='Time', columns='Day', values='Cell_Info')
    
    # Standard ordering for days of the week
    days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    
    # Custom sorting function to handle both standard lecture days (e.g., "Monday") 
    # and multi-week exam days (e.g., "Week 1 - Monday", "Week 2 - Tuesday")
    def day_sorter(d):
        for i, standard_day in enumerate(days_order):
            if standard_day in d:
                week_mod = 0
                if "Week " in d:
                    try:
                        # Extract the week number and multiply by 10 to ensure 
                        # Week 2 days always render after Week 1 days.
                        week_mod = int(d.split("Week ")[1].split(" ")[0]) * 10
                    except:
                        pass
                return week_mod + i
        return 99 # Fallback for unrecognized day formats

    valid_days = sorted([day for day in grid_df.columns], key=day_sorter)
    grid_df = grid_df.reindex(columns=valid_days)
    grid_df = grid_df.fillna("---")
    
    # Render the interactive grid UI
    st.dataframe(grid_df, use_container_width=True, height=500)


def extract_course_details(course_code):
    """
    Parses a standard course code string to extract department, level, and semester.
    Assumes standard Nigerian university naming conventions (e.g., 'CMP 401').
    
    Args:
        course_code (str): The alphanumeric course code.
        
    Returns:
        tuple: (Department string, Level integer, Semester integer)
    """
    try:
        parts = course_code.strip().split()
        dept = parts[0].upper()       # Extract department prefix (e.g., 'CMP')
        number = parts[1]             # Extract numerical code (e.g., '401')
        
        # The first digit of the numerical code dictates the academic level (4 -> 400L)
        level = int(number[0]) * 100  
        # The last digit dictates the semester (Odd = 1st Semester, Even = 2nd Semester)
        semester = 1 if int(number[-1]) % 2 != 0 else 2 
        
        return dept, level, semester
    except Exception as e:
        return None, None, None

# ==========================================
# APPLICATION INITIALIZATION
# ==========================================

# Initialize the SQLite database connection and create tables if they do not exist
init_db()

# Configure the Streamlit Page metadata and layout
st.set_page_config(page_title="RUN Timetable Generator", layout="wide")

st.title("🎓 RUN Automated Timetable System")
st.markdown("---")

# Navigation
st.sidebar.header("Navigation")
menu = st.sidebar.radio("Go to:", ["Dashboard", "Import Data", "Generate Timetable"])

# Fetch live database stats
with Session(engine) as session:
    total_courses = session.query(Course).count()
    total_venues = session.query(Venue).count()


# ==========================================
# PAGE: DASHBOARD
# ==========================================
if menu == "Dashboard":
    st.subheader("System Overview")
    st.success("Database is live and connected.")
    
    col1, col2 = st.columns(2)
    col1.metric("Total Courses in Database", total_courses)
    col2.metric("Total Venues in Database", total_venues)
    
    if total_courses > 0:
        st.write("### Recent Courses")
        with Session(engine) as db_session:
            courses_df = pd.read_sql(db_session.query(Course).statement, db_session.bind)
            st.dataframe(courses_df.drop(columns=['id']).tail()) 


# ==========================================
# PAGE: IMPORT DATA
# ==========================================
elif menu == "Import Data":
    st.subheader("📥 Mass Import System")
    st.write("Upload your Excel or CSV file to populate the database.")
    
    # COURSE IMPORT
    uploaded_file = st.file_uploader("Upload Courses File (CSV or Excel)", type=["csv", "xlsx"])
    
    if uploaded_file is not None:
        try:
            if uploaded_file.name.endswith('.csv'):
                df = pd.read_csv(uploaded_file)
            else:
                df = pd.read_excel(uploaded_file)
                
            st.success("File read successfully! Here is a preview:")
            st.dataframe(df.head())
            st.warning("⚠️ Make sure your columns match the expected names below before saving.")
            
            if st.button("💾 Save Courses to Database", use_container_width=True):
                with st.spinner("Processing and Auto-Extracting details..."):
                    with Session(engine) as db_session:
                        success_count = 0
                        
                        # Iterate through uploaded data and map columns to the Course model
                        for index, row in df.iterrows():
                            try:
                                # Base field extraction with string sanitization
                                raw_code = str(row['Course Code']).strip()
                                raw_title = str(row['Title']).strip()
                                raw_dept = str(row['Department']).strip()
                                raw_students = int(row['Students'])
                                
                                # Category designates core vs elective constraints. Defaults to 'Core'.
                                raw_category = str(row.get('Category', 'Core')).strip() 
                                
                                # Automated attribute extraction for imported course codes
                                parts = raw_code.split()
                                if len(parts) >= 2:
                                    num_part = parts[1]
                                    calculated_level = int(num_part[0]) * 100 
                                    calculated_semester = 1 if int(num_part[-1]) % 2 != 0 else 2
                                else:
                                    calculated_level = 100
                                    calculated_semester = 1
                                    
                                raw_units = int(row.get('Units', 3)) 
                                
                                # Construct the ORM database record
                                new_course = Course(
                                    course_code=raw_code,
                                    title=raw_title,
                                    units=raw_units,
                                    department=raw_dept,
                                    level=calculated_level,
                                    semester=calculated_semester,
                                    estimated_students=raw_students,
                                    category=raw_category
                                )    
                                db_session.add(new_course)
                                success_count += 1
                            except Exception as e:
                                st.error(f"Error on row {index + 2} ({raw_code}): {e}")
                                
                        db_session.commit()
                        st.success(f"✅ Masterful Execution! Successfully committed {success_count} courses.")
        except Exception as e:
            st.error(f"Could not read file: {e}")
      
    # VENUE IMPORT
    st.markdown("---")
    st.subheader("🏢 Mass Import Venues")
    
    venue_file = st.file_uploader("Upload Venues File (CSV or Excel)", type=["csv", "xlsx"], key="venue_uploader")
    
    if venue_file is not None:
        try:
            if venue_file.name.endswith('.csv'):
                v_df = pd.read_csv(venue_file)
            else:
                v_df = pd.read_excel(venue_file)
                
            st.success("Venue file read successfully! Here is a preview:")
            st.dataframe(v_df.head())
            
            if st.button("💾 Save Venues to Database", use_container_width=True):
                with st.spinner("Processing venue capacities..."):
                    with Session(engine) as db_session:
                        venue_success_count = 0
                        
                        for index, row in v_df.iterrows():
                            try:
                                raw_venue_name = str(row['Venue Name']).strip()
                                raw_capacity = int(row['Capacity'])
                                raw_prefixes = str(row['Allowed Prefixes']).strip()
                                raw_type = str(row.get('Venue Type', 'Lecture Hall')).strip()
                                
                                new_venue = Venue(
                                    name=raw_venue_name,
                                    capacity=raw_capacity,
                                    venue_type=raw_type,
                                    allowed_prefixes=raw_prefixes
                                )
                                db_session.add(new_venue)
                                venue_success_count += 1
                            except Exception as e:
                                st.error(f"Error on row {index + 2}: {e}")
                                
                        db_session.commit()
                        st.success(f"✅ Successfully committed {venue_success_count} venues.")
        except Exception as e:
            st.error(f"Could not read venue file: {e}")

    # LECTURER IMPORT
    st.markdown("---")
    st.subheader("👨‍🏫 (Optional) Import Lecturer Allocations")
    
    lec_file = st.file_uploader("Upload Lecturer File (CSV/Excel) [Columns: Course Code, Lecturer]", type=["csv", "xlsx"], key="lec_uploader")
    
    if lec_file is not None:
        try:
            if lec_file.name.endswith('.csv'):
                l_df = pd.read_csv(lec_file)
            else:
                l_df = pd.read_excel(lec_file)
                
            st.dataframe(l_df.head())
            
            if st.button("💾 Map Lecturers to Courses", use_container_width=True):
                with st.spinner("Mapping lecturers to existing courses..."):
                    with Session(engine) as db_session:
                        mapped_count = 0
                        for index, row in l_df.iterrows():
                            raw_code = str(row['Course Code']).strip()
                            raw_lecturer = str(row['Lecturer']).strip()
                            
                            course_to_update = db_session.query(Course).filter(Course.course_code == raw_code).first()
                            
                            if course_to_update:
                                course_to_update.lecturer = raw_lecturer
                                mapped_count += 1
                        db_session.commit()
                        st.success(f"✅ Successfully mapped lecturers to {mapped_count} courses!")
        except Exception as e:
            st.error(f"Could not read lecturer file: {e}")

    # DATABASE MANAGEMENT (DELETE DATA)
    st.markdown("---")
    st.subheader("🗑️ Database Management")
    colA, colB = st.columns(2)
    
    with colA:
        if st.button("🚨 Delete ALL Courses", use_container_width=True):
            with Session(engine) as db_session:
                db_session.query(Course).delete()
                db_session.commit()
                st.success("All courses have been wiped from the database.")
    
    with colB:
        if st.button("🚨 Delete ALL Venues", use_container_width=True):
            with Session(engine) as db_session:
                db_session.query(Venue).delete()
                db_session.commit()
                st.success("All venues have been wiped from the database.")


# ==========================================
# PAGE: GENERATE TIMETABLE
# ==========================================
elif menu == "Generate Timetable":
    st.subheader("⚙️ Timetable Generation Engine")
    st.write("Configure your generation parameters below based on the uploaded session data.")
    
    col1, col2, col3 = st.columns(3)
    with col1:
        timetable_type = st.radio("Select Timetable Type:", ["Lecture Timetable", "Exam Timetable"])
    with col2:
        target_semester = st.radio("Select Semester:", ["1st Semester(Alpha)", "2nd Semester(Omega)"])
    with col3:
        if timetable_type == "Exam Timetable":
            exam_weeks = st.number_input("Exam Period Duration (Weeks)", min_value=1, max_value=4, value=2)
        else:
            exam_weeks = 1
            st.info("Lectures generate on a standard 1-week recurring cycle.")
            
    st.markdown("---")
    sem_int = 1 if target_semester == "1st Semester(Alpha)" else 2
    
    with Session(engine) as db_session:
        target_courses = db_session.query(Course).filter(Course.semester == sem_int).all()
        all_venues = db_session.query(Venue).all()
        
        if len(target_courses) == 0 or len(all_venues) == 0:
            st.warning("⚠️ Missing Data: Ensure you have uploaded both Courses and Venues for this semester.")
        else:
            if st.button(f"🚀 Generate {timetable_type}", use_container_width=True):
                with st.spinner("🧬 Generating timetable... Please wait."):
                    
                    best_schedule = generate_optimal_timetable(target_courses, all_venues, timetable_type, exam_weeks)
                    
                    if best_schedule:
                        st.success(f"🎉 Generated! (Clashes: {best_schedule.clashes}, Fitness Score: {best_schedule.fitness})")
                        
                        table_data = []
                        days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
                        
                        for assignment in best_schedule.assignments:
                            c = assignment['course']
                            v_list = assignment['venues']
                            slot = assignment['slot']
                            venue_names = ", ".join([v.name for v in v_list])
                            
                            # Safely retrieve lecturer mapping; default to "TBA" if unassigned
                            lecturer_name = getattr(c, 'lecturer', None)
                            if not lecturer_name:
                                lecturer_name = "TBA"
                            
                            # --- SLOT DECODING LOGIC ---
                            # The genetic algorithm optimizes using a 1D integer array 'slot' to represent time.
                            # We must dynamically decode this integer back into a human-readable Day and Time structure.
                            
                            if timetable_type == "Exam Timetable":
                                # Exam Constants: 3 sessions per day, 6 days per week (Mon-Sat)
                                day_index = slot // 3
                                week_num = (day_index // 6) + 1
                                day_name = days[day_index % 6]
                                day_str = f"Week {week_num} - {day_name}"
                                
                                session_idx = slot % 3
                                times = ["08:00 AM - 11:00 AM", "12:00 PM - 03:00 PM", "04:00 PM - 07:00 PM"]
                                time_str = times[session_idx]
                            else:
                                # Lecture Constants: 4 sessions per day, 5 days per week (Mon-Fri)
                                day_str = days[slot // 4]
                                session_idx = slot % 4
                                times = ["08:00 AM - 10:00 AM", "10:00 AM - 12:00 PM", "01:00 PM - 03:00 PM", "03:00 PM - 05:00 PM"]
                                time_str = times[session_idx]
                                
                            table_data.append({
                                "Department": c.department,
                                "Course Code": c.course_code,
                                "Title": c.title,
                                "Level": c.level,
                                "Students": c.estimated_students,
                                "Lecturer": lecturer_name,
                                "Day": day_str,
                                "Time": time_str,
                                "Allocated Venue(s)": venue_names
                            })
                            
                        # 1. Convert the generated data into a DataFrame FIRST
                        result_df = pd.DataFrame(table_data)
                        
                        st.markdown("---")
                        st.subheader("📊 View Generated Timetable")
                        
                        # 2. Add Dropdown Filters
                        col_f1, col_f2 = st.columns(2)
                        with col_f1:
                            departments = ["All"] + list(result_df['Department'].unique())
                            dept_filter = st.selectbox("Filter by Department", departments)
                        with col_f2:
                            levels = ["All"] + sorted(list(result_df['Level'].unique()))
                            level_filter = st.selectbox("Filter by Level", levels)
                            
                        # 3. Apply Filters
                        filtered_df = result_df.copy()
                        if dept_filter != "All":
                            filtered_df = filtered_df[filtered_df['Department'] == dept_filter]
                        if level_filter != "All":
                            filtered_df = filtered_df[filtered_df['Level'] == level_filter]
                            
                        if filtered_df.empty:
                            st.info("No courses match this filter combination.")
                        else:
                            # 4. Display the Beautiful Grid Matrix!
                            display_timetable_grid(filtered_df)
                            
                            # 5. Display the raw list in a hidden expander below the grid
                            with st.expander("Show Raw List View"):
                                if timetable_type == "Lecture Timetable":
                                    day_order = {day: i for i, day in enumerate(days)}
                                    sorted_df = result_df.sort_values(key=lambda col: col.map(day_order) if col.name == 'Day' else col)
                                else:
                                    sorted_df = result_df.sort_values(by=['Day', 'Time'])
                                    
                                st.dataframe(sorted_df, use_container_width=True)
                        
                        # 6. Download Button
                        csv = result_df.to_csv(index=False).encode('utf-8')
                        st.download_button(
                            label="📥 Download Complete Timetable as CSV",
                            data=csv,
                            file_name=f"{timetable_type}_{target_semester}.csv",
                            mime="text/csv",
                        )
                    else:
                        st.error("Algorithm failed to generate a schedule.")